AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Our CS3733 Group Project: BigTicket

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: "BigTicketAPI"
      StageName: "prod"
      Cors:
        AllowMethods: "'OPTIONS, POST, GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'" #DO NOT USE THIS VALUE IN PRODUCTION - https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-cors.html

  CreateVenue:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "Create-Venue"
      CodeUri: backend/
      Handler: create-venue.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Role: arn:aws:iam::514083196121:role/ExecuteCode
      VpcConfig:
        SecurityGroupIds:
          - sg-065e0b8d755a33fa7
        SubnetIds:
          - subnet-02d357301c4fc629b
          - subnet-054357d0c8c455bf9
          - subnet-00d51aa75d59a4f91
      Events:
        CreateVenue:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-venue
            Method: POST
            RestApiId:
              Ref: API
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - create-venue.ts
